### ISSUE TITLE
The bibtex entry is not valid for 2022_Evgeni_Designing

### ISSUE THREAD

**Issue by luiscruz** [luiscruz/course_sustainableSE#3]
The bibtex entry is not valid for 2022_Evgeni_Designing. Can you double check? @LvKvA

_Originally posted by @luiscruz in https://github.com/luiscruz/course_sustainableSE/issues/1#issuecomment-1038033235_

**Comment by LvKvA** [comment]
Apologies, the issue should be fixed in our new Pull Request #8.

**Comment by luiscruz** [comment]
Thanks!
